# Generated by Django 4.2.11 on 2024-03-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service',
        ),
    ]
