# Generated by Django 4.2.11 on 2024-03-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customer_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='package',
        ),
    ]
