# Generated by Django 4.2.11 on 2024-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_customer_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='package',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
