# Generated by Django 4.2.11 on 2024-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customer_dry_customer_gravy_customer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dry',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gravy',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='roti',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
