# Generated by Django 4.2.11 on 2024-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='named',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='regular',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
