# Generated by Django 4.2.11 on 2024-03-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_customer_named_customer_regular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='package',
        ),
    ]
