# Generated by Django 4.2.11 on 2024-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='route',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
