# Generated by Django 4.2.11 on 2024-03-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_tiffin_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tiffin',
        ),
    ]
