# Generated by Django 4.2.11 on 2024-03-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_delete_tiffin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiffin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roti', models.IntegerField(default=0)),
                ('dry', models.IntegerField(default=0)),
                ('gravy', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('custom', 'Custom')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
    ]
