# Generated by Django 4.2.11 on 2024-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_tiffin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dry',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gravy',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='named',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='regular',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='roti',
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
