# Generated by Django 4.2.11 on 2024-03-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_customer_dry_remove_customer_gravy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, null=True),
        ),
    ]
