# Generated by Django 4.2.11 on 2024-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_customer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='rice',
            field=models.IntegerField(default=0),
        ),
    ]
